### ISSUE TITLE
Support launching an app/screen directly

### ISSUE THREAD

**Issue by jackwilsdon** [InfiniTimeOrg/InfiniSim#112]
As the title says - it'd be good if an app/screen could be launched directly at startup. This would help improve the feedback loop whilst developing new features.

**Comment by NeroBurner** [comment]
This should be already possible as the number key already are bound to specific screens. Would Elit be enough for your usecase to programatically locally "rebind" one of the number keys?

**Comment by NeroBurner** [comment]
Closed due to inactivity

**Comment by jackwilsdon** [comment]
Apologies for the late reply on this. I didn't realise specific apps could be launched via the number keys - that's definitely useful. Is it possible to launch any apps after app 9? If not, it seems like a command line flag might still be useful (and would be useful for development anyway, allowing for launching straight into an app from the command line).

**Comment by jackwilsdon** [comment]
> A general switch wouldn't be feasible as we have more than 20 screens, and which ones do we select?

Unless I'm misunderstanding, what prevents a command line flag like `-screen 9` being added? Having to refer to the screens by ID is not the most ideal, but it keeps it flexible (and means that a list of screen names isn't heeded).

**Comment by NeroBurner** [comment]
I'm sorry, I may am slow at the uptake here. Which screen would be launched by defining `-screen 9`? Could you describe what actions you would take in your scenario and what you would then expect to happen?
