### ISSUE TITLE
Typescript not installed

### ISSUE THREAD

**Issue by JosuGZ** [InfiniTimeOrg/InfiniSim#123]
My build is failing due not having typescript installed. Installing typescript (`npm install typescript`) causes another issue.

Could a package-lock.json be added? And can anybody share which exact version of typescript will work?

**Comment by FintasticMan** [comment]
See InfiniTimeOrg/InfiniTime#1764. There is work being done on a Python port of at least lv_img_conv, to fix a number of issues we've had with Node.

**Comment by NeroBurner** [comment]
Fixed with https://github.com/InfiniTimeOrg/InfiniTime/pull/1863
