### ISSUE TITLE
Implement Screen Transitions like on the real PineTime

### ISSUE THREAD

**Issue by CoderThomasB** [InfiniTimeOrg/InfiniSim#13]
On the real Pinetime, there is a little animation for scrolling that doesn't show up on the simulated. I assume it's because the clock speed on my laptop is way faster than the Pinetime. Is it possible to purposely slow down the speed of the code to simulate the speed of the real Pinetime and therefore display the animations?

**Comment by NeroBurner** [comment]
It's not the speed, it's just the lack of switching animation :see_no_evil: 

I haven't implemented the screen switching animations and I don't quite know how. As far as I know the pinetime has some kind of hardware support for this switching, but I don't know much more about it.

Would be really awesome if the switching could get implemented

**Comment by NeroBurner** [comment]
maybe the screen loading API can help https://docs.lvgl.io/7.11/overview/object.html#load-screens

**Comment by NeroBurner** [comment]
Fixed with #37 

![2022-06-13_screen_switching](https://user-images.githubusercontent.com/9076163/173450763-118c9914-eec2-45fe-9417-311af17cb562.gif)
