### ISSUE TITLE
Watchface Infinineat and Casio G7710 greyed out - fonts issues?

### ISSUE THREAD

**Issue by metaphys** [InfiniTimeOrg/InfiniSim#158]
I can’t seem to test those watchfaces on the simulator. They are greyed out. Since they are the 2 watchfaces with custom fonts I’m suspectiting this is the issue. I’m trying to reuse the fonts from Casio G7710 but it doesn’t seem to work either. Is there something specific to do in order to have the fonts available in infinisim aside from `npm install lv_font_conv@1.5.2`?

**Comment by NeroBurner** [comment]
you'll need to load the ressources.zip into the spi-raw image by running `littlefs-do` helper executable in the same directory as you run `infinisim`

https://github.com/InfiniTimeOrg/InfiniSim?tab=readme-ov-file#littlefs-do-helper

**Comment by metaphys** [comment]
Thank you for your answer, where can I find the ressources.zip file?

**Comment by metaphys** [comment]
so I found a build/resources/infinitime-resources-1.14.0.zip file
I loaded it with `build/littlefs-do res load build/resources/infinitime-resources-1.14.0.zip`
but now I have a segfault on launching infinisim. Am I still missing something?

**Comment by metaphys** [comment]
ok starting from a fresh InfiniTIme dir, there is no more segfault so the problem is from my code now.
Thank you for your help on the infinitime-resources-1.14.0.zip file. Maybe the documentation could be improve to indicate the location and name of the file.

**Comment by NeroBurner** [comment]
PR welcome ;)
