### ISSUE TITLE
FS Stat() function breaks when using paths that start with /

### ISSUE THREAD

**Issue by Arsen6331** [InfiniTimeOrg/InfiniSim#23]
When using a path starting with `/`, the `Stat()` function does not detect the file. I imagine it's trying to look in the root of my computer's filesystem. Instead, if a leading slash exists, it should be trimmed, like in the `FileOpen()` function.

**Comment by NeroBurner** [comment]
Absolute paths are trimmed to be paths relative to the working directory.

```cpp
  const char *local_filename = fileName[0]=='/' ? &fileName[1] : fileName;
```

See https://github.com/InfiniTimeOrg/InfiniSim/blob/main/sim/components/fs/FS.cpp#L63

Please provide more more info what you are doing and what isn't working

**Comment by Arsen6331** [comment]
It seems to be specifically the Stat() function that isn't working. I should've been more specific.

**Comment by NeroBurner** [comment]
THAT is totally plausible! It is new code and I didn't watch out for the relative path thingy. 

Please update the description and title of the issue to reflect that the stat function is faulty.

And a PR is very welcome :)
