### ISSUE TITLE
Problem building on WSL

### ISSUE THREAD

**Issue by joshuaalm** [InfiniTimeOrg/InfiniSim#44]
I realize WSL isn't currently supported, and I will try working this out on my own and update here.

I use Debian WSL on Windows 11.  When running `cmake --build build -j4` I received the following error:

```
CMake Error at InfiniTime/src/displayapp/fonts/CMakeLists.txt:4 (find_program):
  Could not find LV_FONT_CONV using the following names: lv_font_conv,
  NO_CACHE
```

**Comment by joshuaalm** [comment]
I simply hadn't installed lv_font_conv, as was linked.

**Comment by NeroBurner** [comment]
good you've found it :)

**Comment by NeroBurner** [comment]
does it now work in wsl?

**Comment by joshuaalm** [comment]
Sorry for the delay.  Yes, it does!

**Comment by TailyFair** [comment]
Also works with Ubuntu WSL2 on Windows 11.
