### ISSUE TITLE
Increasing brightness while screen is off seems to freeze sim

### ISSUE THREAD

**Issue by joshuaalm** [InfiniTimeOrg/InfiniSim#45]
While testing the input buttons and trying to remind myself of the sim indicator screen layout, I managed to increase the brightness.  Indicator on second window showed an increase from one white circle to two white circles, but after that nothing seemed to respond.  I suspended the job from the terminal in order to exit.

**Comment by NeroBurner** [comment]
thanks for pointing out the issue. Finally came around to mitigate the problem
