### ISSUE TITLE
GIF recording renders colors & icons differently. Also timing deviates.

### ISSUE THREAD

**Issue by mashuptwice** [InfiniTimeOrg/InfiniSim#51]
The GIF recording seems to interpret some colors as black, some icons in a distorted way and sometimes visual artifacts. 

In the following video note the grainy heartrate symbol in the lower-left, the color of the battery icon and the shape of the charger icon in the upper right, as well as the artifacts in the upper left corner.

https://user-images.githubusercontent.com/54219098/184676442-30624754-f4bb-49dd-9cf2-5040b53fd84d.mp4

Also the timing deviates between the realtime window recording and the GIF. While the two videos are in sync in the beginning, they start to shift very quickly.

It seems that the code which maps the "real" colors to a GIF 256 color map is misinterpreting some stuff.

For discovery of the bug refer to [InfiniTime PR #1276](https://github.com/InfiniTimeOrg/InfiniTime/pull/1276).

**Comment by NeroBurner** [comment]
@faxe1008 found the issue and fixed it with a one-line-change https://github.com/InfiniTimeOrg/InfiniSim/pull/77

It seemingly was the "dithering" I unknowingly activated, which introduced the artifacts
