### ISSUE TITLE
Date library removed from InfiniTime

### ISSUE THREAD

**Issue by Riksu9000** [InfiniTimeOrg/InfiniSim#88]
The date library has been removed in InfiniTime. InfiniSim seems to be using this library through InfiniTime. What do you want to do about this? Should the library be removed from InfiniSim as well, or should it be added directly here?

**Comment by NeroBurner** [comment]
replaced the date/date.h include by using ctimes put_time function, pushing fix soon. SystemTask and DisplayApp constructors have changed and need to be updated as well
